# Generated by Django 3.2 on 2022-09-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_at_least_one_product',
            field=models.BooleanField(default=False),
        ),
    ]
