# Generated by Django 3.2 on 2022-11-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_category_has_at_least_one_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_details',
            field=models.TextField(default=''),
        ),
    ]
